openapi: 3.0.1
info:
  title: API Antecipação de Recebíveis
  description: 'Esta é a especificação técnica da API de Antecipação de Recebíveis para implementação por Parceiros (debtors) do Banco Randon.'
  contact:
    email: developers@randon.com.br
  version: 1.0.4
tags:
- name: document
  description: Gestão de Títulos de Contas a Pagar relacionados a Notas Fiscais
- name: seller
  description: Gestão de dados cadastrais de Cedentes de Títulos (Fornecedores ou Beneficiários)
- name: juridicalPerson
  description: Gestão de documentos de Pessoas Jurídicas
- name: naturalPerson
  description: Gestão de documentos de Pessoas Físicas
paths:
  /documents/list:
    get:
      tags:
      - document
      summary: Listar todos Títulos
      description: Lista todos os Títulos de Contas a Pagar do Sacado (Parceiro ou Pagador) disponíveis para serem antecipados pelos Cedentes
      operationId: listDocuments
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DocumentExtended'
  /documents/{sellerId}/list:
    get:
      tags:
      - document
      summary: Listar Títulos de Cedente (Fornecedor ou Beneficiário)
      description: Lista todos os Títulos de Contas a Pagar do Sacado (Parceiro ou Pagador) disponíveis para serem antecipados por um Cedente (Fornecedor ou Beneficiário) específico
      operationId: listSellerDocuments
      parameters:
      - name: sellerId
        in: path
        description: CNPJ do Cedente (Fornecedor ou Beneficiário)
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DocumentExtended'
        '400':
          description: Invalid seller id (CNPJ inválido)
          content: {}
        '404':
          description: Seller not found (Cedente não encontrado)
          content: {}
  /documents/claim:
    post:
      tags:
      - document
      summary: Registrar Títulos como antecipados
      description: Registra os Títulos de Contas a Pagar como antecipados para formalizar a alteração de titularidade
      operationId: setDocumentsClaimed
      requestBody:
        description: Contrato contendo a Lista de Títulos de Contas a Pagar antecipados (*vendidos*, *claimed*)
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Contract'
        required: true
      responses:
        200:
          description: OK
          content: {}
        404:
          description: Documents not found (Documentos não encontrados)
          content: 
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DocumentBasic'
  /sellers:
    get:
      tags:
      - seller
      summary: Listar todos os Cedentes de Títulos (Fornecedores ou Beneficiários)
      description: Lista todos os Cedentes de Títulos (Fornecedores ou Beneficiários) com relacionamento com o Parceiro que deram consentimento para o compartilhamento de dados com o Banco Randon.
      operationId: getSellers
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Seller'
  /juridical-person/{id}/documents:
    get:
      tags:
      - juridicalPerson
      summary: Listar documentos de uma Pessoa Jurídica
      description: "Listar todos os documentos de contituição de uma Pessoa Jurídica (e.g., Empresa do Cedente de Títulos (Fornecedor ou Beneficiário)).      
                    <br>
                    Sociedade de Responsabilidade Limitada (Ltda):<br>
                    - Contrato Social (última atualização)<br>
                    <br>
                    Sociedade Anônima (S.A.):<br>
                    - Estatuto Social<br>
                    - Ata Eleição da Diretoria<br>
                    - Quadro Societário<br>
                    <br>
                    Empresário Individual (EI):<br>
                    - Requerimento do Empresário<br>
                    <br>
                    Microempreendedor Individual (MEI):<br>
                    - CCMEI (Certificado da Condição do Microempreendedor Individual)<br>
                    <br>
                    Empresa Individual de Responsabilidade Limitada (EIRELI):<br>
                    - Contrato Social<br>
                    - Ata Eleição da Diretoria<br>
                    <br>
                    Cooperativas:<br>
                    - Estatuto Social<br>
                    - Ata Eleição da Diretoria"
      operationId: getJuridicalPersonDocuments
      parameters:
      - name: id
        in: path
        description: CNPJ da Pessoa Jurídica
        required: true
        schema:
          type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                description: "Documentos de uma Pessoa Jurídica"
                items:
                  $ref: '#/components/schemas/JuridicalPersonDocument'
  /natural-person/{id}/documents:
    get:
      tags:
      - naturalPerson
      summary: Listar documentos de uma Pessoa Física
      description: "Listar todos os documentos de uma Pessoa Física.
                    <br><br>
                    Arquivos representantes legais e procuradores:
                    <br>
                    - Arquivo de Documento de Identificação Pessoal (CNH ou RG)<br>
                    - Comprovante de endereço<br>
                    - Procuração"
      operationId: getNaturalPersonDocuments
      parameters:
      - name: id
        in: path
        description: CPF da Pessoa Física
        required: true
        schema:
          type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                description: "Documentos de uma Pessoa Física"
                items:
                  $ref: '#/components/schemas/NaturalPersonDocument'
components:
  schemas:
    Address:
      type: object
      required:
      - line1
      - number
      - city
      - state
      - zipCode
      properties:
        line1:
          type: string
          description: "Logradouro (Rua, Avenida, etc.)"
        number:
          type: string
          description: "Número"
        line2:
          type: string
          description: "Complemento"
        city:
          type: string
          description: "Cidade"
        state:
          type: string
          description: "Sigla da Unidade Federativa (RS, SC, SP, etc.)"
        zipCode:
          type: string
          description: "CEP"
    Client:
      type: object
      description: "Cliente de Fornecedor"
      required:
      - name
      - shareOfRevenue
      properties:
        name:
          type: string
          description: "Nome do cliente"
        shareOfRevenue:
          type: number
          format: double
          description: "Percentual do faturamento que esse cliente concentra."
    Consent:
      type: object
      description: "Consentimento (aceite) do Fornecedor (Seller) para que o Parceiro (Debtor) compartilhe informações com o Banco Randon."
      required:
      - datetime
      properties:
        datetime:
          type: string
          description: "Data do consentimento (formato conforme RFC 3339, seção 5.6 https://tools.ietf.org/html/rfc3339#section-5.6)"
          example: "2021-01-25T17:32:28Z"
          format: date-time
        ip:
          type: string
          description: "Endereço de IP (Internet Protocol) do usuário que realizou o consentimento"
          example: "185.211.103.56"
        userId:
          type: string
          description: "Identificador de usuário (no sistema do Parceiro) que realizou o consentimento"
    Contract:
      type: object
      required:
      - contractId
      - documents
      properties:
        contractId:
          type: string
          description: "Número do Contrato de Antecipação de Recebíveis"
        contractDate:
          type: string
          description: "Data do Contrato de Antecipação de Recebíveis"
          example: "2021-01-01"
          format: date
        discountRate:
          type: number
          description: "Taxa de desconto aplicada no Contrato de Antecipação de Recebíveis"
          format: double
          example: 1.5
        documents:
          description: "Títulos de Contas a Pagar"
          type: array
          items:
            $ref: '#/components/schemas/DocumentBasic'
    DocumentBasic:
      type: object
      required:
      - invoiceId
      - invoiceSeries
      - sellerId
      - debtorId
      - documentId
      - documentInstallment
      - dueDate
      - netAmount
      properties:
        documentId:
          type: string
          description: "Identificador do Título de Contas a Pagar relacionado à Nota Fiscal"
        documentInstallment:
          type: integer
          description: "Número da Parcela do Título de Contas a Pagar"
        invoiceId:
          type: integer
          description: "Número da Nota Fiscal"
          format: int64
        invoiceSeries:
          type: integer
          description: "Série da Nota Fiscal"
          format: int64
        sellerId:
          type: string
          description: "Número do CNPJ (apenas algarismos) do Cedente do Título (Fornecedor ou Beneficiário) que emitiu a Nota Fiscal"
          example: "00000000000191"
        netAmount:
          type: number
          description: "Valor Líquido da Parcela do Título de Contas a Pagar, ou seja, o valor possível de ser antecipado pelo Cedente"
    DocumentExtended:
      allOf:
        - $ref: '#/components/schemas/DocumentBasic'
        - type: object
          required:
          - debtorId
          - dueDate
          properties:
            debtorId:
              type: string
              description: "Número do CNPJ do Sacado do Título (Parceiro ou Pagador) contra o qual a Nota Fiscal foi emitida (apenas algarismos)"
              example: "00000000000191"
            invoiceAccessKey:
              type: string
              description: "Chave de Acesso da Nota Fiscal eletrônica (44 dígitos)"
              example: "43201092016757006122552000000163666691778287"
            invoiceDate:
              type: string
              description: "Data de emissão da Nota Fiscal"
              example: "2021-01-01"
              format: date
            dueDate:
              type: string
              description: "Data de vencimento da Parcela do Título de Contas a Pagar"
              example: "2021-01-01"
              format: date
    JuridicalPersonDocument:
      type: object
      description: "Documento de Pessoa Jurídica"
      properties:
        type:
          type: string
          description: "Tipo do documento de Pessoa Jurídica"
          enum:
          - contratoSocial
          - estatutoSocial
          - ataEleicaoDiretoria
          - quadroSocietario
          - requerimentoEmpresario
          - ccmei
        file:
          type: string
          description: "Arquivo do Documento"
          format: binary
    NaturalPersonBasic:
      type: object
      description: "Dados cadastrais (profile) de uma Pessoa Física"
      required:
      - id
      - name
      properties:
        id:
          type: string
          description: "Número do CPF (Cadastro de Pessoa Física) somente em algarismos (11 caracteres)"
          example: "12345678910"
        name:
          type: string
          description: "Nome Completo da Pessoa"
    NaturalPersonExtended:
      allOf:
        - $ref: '#/components/schemas/NaturalPersonBasic'
        - type: object
          required:
          - dateOfBirth
          - nationality
          - civilStatus
          - motherName
          - address
          - monthlyIncome
          - profession
          properties:
            dateOfBirth:
              type: string
              description: "Data de Nascimento no formato (YYYY-MM-DD)"
              example: "1980-05-28"
              format: date
            nationality:
              type: string
              description: "Nacionalidade"
              example: "Brasileira"
            civilStatus:
              type: string
              description: "Estado Civil"
              enum:
              - single
              - married
              - divorced
              - widowed
            motherName:
              type: string
              description: "Nome Completo da Mãe"
            profession:
              type: string
              description: "Profissão"
            address:
              type: object
              description: "Endereço Residencial"
              allOf:
                - $ref: '#/components/schemas/Address'
            phone:
              type: string
              description: "Telefone no formato 2 caracteres para DD e 8 ou 9 caracteres para o número (DDNNNNNNNNN)"
              example: "5432394600"
            email:
              type: string
              description: "E-mail"
            monthlyIncome:
              type: number
              description: "Renda ou Salário Mensal"
              format: double
              example: "8930.37"
    NaturalPersonDocument:
      type: object
      description: "Documento de Pessoa Física"
      properties:
        type:
          type: string
          description: "Tipo do documento de Pessoa Física
                        <br><br>
                        id: Arquivo de Documento de Identificação Pessoal (CNH ou RG)
                        <br>
                        address: Arquivo de Comprovante de Endereço
                        <br>
                        proxyStatement: Arquivo de Procuração do Representante legal"
          enum:
          - id
          - address
          - proxyStatement
        file:
          type: string
          description: "Arquivo"
          format: binary
    Partner:
      description: "Sócio de empresa"
      required:
      - name
      allOf:
        - $ref: '#/components/schemas/NaturalPersonBasic'
        - type: object
          required:
          - dateOfBirth
          - nationality
          - civilStatus
          - motherName
          - address
          - monthlyIncome
          properties:
            partnershipEquity:
              type: string
              description: "Percentual de participação do sócio na empresa"
    Proxy:
      description: "Representante legal da empresa"
      required:
      - name
      allOf:
        - $ref: '#/components/schemas/NaturalPersonExtended'
        - type: object
          required:
          - fileId
          - fileAddress
          properties:
            fileId:
              type: string
              description: "Arquivo de Documento de Identificação Pessoal (CNH ou RG)"
            fileAddress:
              type: string
              description: "Arquivo de Comprovante de Endereço"
            fileProxy:
              type: string
              description: "Arquivo de Procuração do Representante legal"
    Seller:
      type: object
      description: "Dados básicos do Cedente do Título (Fornecedor ou Beneficiário)"
      required:
      - id
      - name
      - startDate
      - type
      - annualRevenue
      - address
      - phone
      - email
      - consent
      - partners
      - proxies
      - clients
      properties:
        id:
          type: string
          description: "Número do CNPJ (apenas algarismos) do Cedente do Título (Fornecedor ou Beneficiário) que emitiu a Nota Fiscal"
          example: "00000000000191"
        name:
          type: string
          description: "Razão social"
        startDate:
          type: string
          description: "Data de Constituição da Empresa"
          example: "2021-01-01"
          format: date
        type:
          type: string
          description: "Natureza Jurídica da Empresa.
                      <br><br>
                      ltda: Sociedade de Responsabilidade Limitada<br>
                      sa: Sociedade Anônima<br>
                      ei: Empresário Individual<br>
                      mei: Microempreendedor Individual<br>
                      eireli: Empresa Individual de Responsabilidade Limitada<br>
                      "
          enum:
          - ltda
          - sa
          - ei
          - mei
          - eireli
        annualRevenue:
          type: number
          description: "Faturamento do últimos 12 meses em Reais"       
        address:
          type: object
          description: "Endereço da sede da empresa"
          allOf:
            - $ref: '#/components/schemas/Address'
        phone:
          type: string
          description: "Telefone no formato 2 caracteres para DD e 8 ou 9 caracteres para o número (DDNNNNNNNNN)"
          example: "5432394600"
        email:
          type: string
          description: "E-mail"
        consent:
          type: object
          description: "Consentimento para compartilhamento de informações"
          allOf:
            - $ref: '#/components/schemas/Consent'
        partners:
          type: array
          description: "Sócios da Empresa"
          items:
            $ref: '#/components/schemas/Partner'
        proxies:
          type: array
          description: "Representantes legais (É obrigatório informar os dados dos sócios com participação societária acima de 25%, representantes legais e procuradores caso exista)"
          items:
            $ref: '#/components/schemas/Proxy'
        clients:
          type: array
          description: "Principais clientes (pelo menos 3)"
          items:
            $ref: '#/components/schemas/Client'